# Generated by Django 4.2.6 on 2023-10-30 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentavailability',
            name='vote_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выбора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentavailability',
            name='week',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
