# Generated by Django 4.2.6 on 2023-10-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_studentavailability_vote_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='info',
            field=models.TextField(max_length=200, verbose_name='Командная инфа'),
        ),
    ]
