# Generated by Django 4.2.6 on 2023-10-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_studentavailability_vote_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.JSONField(default=list, verbose_name='Подходящее время')),
                ('week', models.CharField(max_length=20, verbose_name='Дата начала')),
                ('vote_date', models.DateField(verbose_name='Дата выбора')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.student')),
            ],
            options={
                'unique_together': {('student', 'project')},
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='info',
            field=models.TextField(max_length=200, verbose_name='Командная инфа'),
        ),
        migrations.DeleteModel(
            name='StudentAvailability',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
