# Generated by Django 4.2.6 on 2023-10-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_alter_project_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student_count',
            field=models.IntegerField(verbose_name='Размер группы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='week',
            field=models.CharField(max_length=200, verbose_name='Недели'),
        ),
    ]
