# Generated by Django 4.2.6 on 2023-10-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_team_rank_alter_student_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ManyToManyField(to='teamapp.projectmanager', verbose_name='Менеджер'),
        ),
    ]
