# Generated by Django 4.2.6 on 2023-10-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_alter_project_student_count_alter_project_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='week',
            field=models.JSONField(blank=True, default=list, verbose_name='Недели'),
        ),
    ]
